### ISSUE TITLE
[Suggestion] Cache available pokemon in a DB or XML file

### ISSUE THREAD

**Issue by Dracon23** [earshel/PokeyPyManager#10]
I've been giving the latest clone a spin, after figuring out one or two things about usability, and keep hitting a rate limit.

Insteald of polling the API each time you refresh the inventory, you could "cache" the pokemon in a sqlite in-memory database or something like that.

**Comment by earshel** [comment]
Technically, the inventory is already stored in a json file @ /static/inventory.json. I suppose I could make it necessary to press a 'refresh from server' button  to refresh the data rather than each time the page loads, or if the json file is older than x minutes?

**Comment by Dracon23** [comment]
That's what I thought about. Cept for JSON, never really liked that ;F

**Comment by Dracon23** [comment]
One thing is for sure, "every time the page loads" is harsh on the API and invites a hard ban coming the way of the user.

**Comment by earshel** [comment]
I just pushed a new commit implementing the cache system. It seems to work well. 

Inventory data is now cached. New data is requested from the server under the following conditions:
- On startup
- After performing an action (release/rename/etc)
- If user requests new data (button added to interface)
- If cached data is more than x seconds old, where x is the time since the inventory.json file was last updated

**Comment by Dracon23** [comment]
Release/rename are operations that can happen locally, based in what is returned from the api

**Comment by Dracon23** [comment]
Other then that, looking okay.
